#!/usr/bin/env python3
"""Generate app_en.arb and app_ar.arb from extracted strings."""

import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)
L10N_DIR = os.path.join(PROJECT_DIR, 'lib', 'l10n')

# Load extracted strings
with open(os.path.join(SCRIPT_DIR, 'clean_strings.json'), 'r', encoding='utf-8') as f:
    strings = json.load(f)

# Arabic translation dictionary - comprehensive translations for a Lebanese delivery app
AR_TRANSLATIONS = {
    # Auth & Account
    "about": "حول",
    "accept": "قبول",
    "acceptingOrders": "قبول الطلبات",
    "accessDenied": "تم رفض الوصول",
    "accessDenied2": "تم رفض الوصول",
    "accessDeniedAdminPrivilegesRequired": "تم رفض الوصول. صلاحيات المسؤول مطلوبة.",
    "accessDeniedDriverPrivilegesRequired": "تم رفض الوصول. صلاحيات السائق مطلوبة.",
    "account": "الحساب",
    "accountCreatedPleaseVerifyYourEmail": "تم إنشاء الحساب! يرجى التحقق من بريدك الإلكتروني.",
    "active": "نشط",
    "activeHours": "ساعات النشاط",
    "activeOrders": "الطلبات النشطة",
    "activeToday": "نشط اليوم",
    "activeUsers": "المستخدمون النشطون",
    "acrossAllDrivers": "عبر جميع السائقين",
    "add": "إضافة",
    "addACommentOptional": "أضف تعليقاً (اختياري)",
    "addAddress": "إضافة عنوان",
    "addCategory": "إضافة فئة",
    "addNewBannerPromotion": "إضافة لافتة/ترويج جديد",
    "addNewProduct": "إضافة منتج جديد",
    "addNewStore": "إضافة متجر جديد",
    "addPhoto": "إضافة صورة",
    "addPlan": "إضافة خطة",
    "addProduct": "إضافة منتج",
    "addProduct2": "إضافة منتج",
    "addStore": "إضافة متجر",
    "addSubcategory": "إضافة فئة فرعية",
    "addThumbnailOptional": "إضافة صورة مصغرة (اختياري)",
    "addToCart": "أضف إلى السلة",
    "addYourDeliveryAddressesForFaster": "أضف عناوين التوصيل لعملية دفع أسرع",
    "addYourFirstAddress": "أضف عنوانك الأول",
    "addYourFirstProductToStart": "أضف أول منتج لبدء البيع",
    "addEditCategories": "إضافة/تعديل الفئات",
    "additionalNotesOptional": "ملاحظات إضافية (اختياري)",
    "address": "العنوان",
    "addressAdded": "تمت إضافة العنوان",
    "addressDeleted": "تم حذف العنوان",
    "addressDetails": "تفاصيل العنوان",
    "addressLabel": "تسمية العنوان",
    "addressUpdated": "تم تحديث العنوان",
    "admin": "المسؤول",
    "adminAccessRequired": "صلاحيات المسؤول مطلوبة",
    "adminCategories": "فئات المسؤول",
    "adminDashboard": "لوحة تحكم المسؤول",
    "adminMode": "وضع المسؤول",
    "adminPanel": "لوحة المسؤول",
    "adminCategories2": "المسؤول • الفئات",
    "adsPromotions": "الإعلانات والعروض",
    "adsManagement": "إدارة الإعلانات",
    "adsManager": "مدير الإعلانات",
    "adBanner": "لافتة إعلانية",
    "adBannerPreview": "معاينة اللافتة الإعلانية",
    "adDeletedSuccessfully": "تم حذف الإعلان بنجاح",
    "adTitle": "عنوان الإعلان",
    "aiMate": "المساعد الذكي",
    "aiMateYourSmartAssistant": "المساعد الذكي – مساعدك الذكي",
    "aiRequestTimedOutPleaseTry": "انتهت مهلة طلب الذكاء الاصطناعي. يرجى المحاولة مرة أخرى.",
    "all": "الكل",
    "allDriverApplicationsHaveBeenProcessed": "تمت معالجة جميع طلبات السائقين.",
    "allMerchantApplicationsHaveBeenProcessed": "تمت معالجة جميع طلبات التجار.",
    "allRoles": "جميع الأدوار",
    "allServicesRunningNormally": "جميع الخدمات تعمل بشكل طبيعي",
    "allStatus": "جميع الحالات",
    "allTime": "كل الأوقات",
    "allTimeCompleted": "المكتملة على الإطلاق",
    "analytics": "التحليلات",
    "analyticsOverview": "نظرة عامة على التحليلات",
    "anyAdditionalInformationYouWouldLike": "أي معلومات إضافية تود تقديمها",
    "appConfiguration": "إعدادات التطبيق",
    "appPreferences": "تفضيلات التطبيق",
    "applicationSubmittedSuccessfully": "تم تقديم الطلب بنجاح!",
    "applications": "الطلبات",
    "apply": "تطبيق",
    "applyAsMerchant": "التقدم كتاجر",
    "approve": "موافقة",
    "approveDriver": "الموافقة على السائق",
    "approveMerchant": "الموافقة على التاجر",
    "archive": "أرشيف",
    "archiveConversation": "أرشفة المحادثة",
    "areYouSureYouWantTo": "هل أنت متأكد أنك تريد إلغاء هذا الحجز؟",
    "areYouSureYouWantTo2": "هل أنت متأكد أنك تريد إلغاء هذا الطلب؟",
    "areYouSureYouWantTo3": "هل أنت متأكد أنك تريد إلغاء اشتراكك؟",
    "areYouSureYouWantTo4": "هل أنت متأكد أنك تريد حذف هذا الإعلان؟",
    "areYouSureYouWantTo5": "هل أنت متأكد أنك تريد إزالة جميع المنتجات من سلتك؟",
    "areYouSureYouWantTo6": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    "areYouSure": "هل أنت متأكد؟",
    "askAiCheapItalianFoodOpen": "اسأل الذكاء الاصطناعي: \"طعام إيطالي رخيص مفتوح الآن\"",
    "assignDriver": "تعيين سائق",
    "assignOrders": "تعيين طلبات",
    "assignOrdersToDriver": "تعيين طلبات للسائق",
    "assignToAStoreCategoryOr": "تعيين لفئة متجر أو اتركه فارغاً",
    "assignToStore": "تعيين لمتجر *",
    "assignedOrders": "الطلبات المعينة",
    "assigningOrders": "جارٍ تعيين الطلبات...",
    "assignmentBlockedDriverIsNoLonger": "تم حظر التعيين — السائق لم يعد متاحاً",
    "averageRating": "متوسط التقييم",
    "avgOrderValue": "متوسط قيمة الطلب",
    "avgOrder": "متوسط/طلب",
    "awaitingAssignment": "بانتظار التعيين",
    "back": "رجوع",
    "backToApp": "العودة للتطبيق",
    "backToHome": "العودة للرئيسية",
    "baseFare": "الأجرة الأساسية",
    "becomeADriver": "كن سائقاً",
    "becomeAMerchant": "كن تاجراً",
    "becomeAPartner": "كن شريكاً",
    "billingCycle": "دورة الفوترة",
    "bookNow": "احجز الآن",
    "bookService": "حجز خدمة",
    "bookingCancelled": "تم إلغاء الحجز",
    "bookingCreatedSuccessfully": "تم إنشاء الحجز بنجاح",
    "broadcastMessageToAllUsers": "رسالة جماعية لجميع المستخدمين",
    "browseAllStores": "تصفح جميع المتاجر",
    "browseApp": "تصفح التطبيق",
    "browseItemsAndAddThemTo": "تصفح المنتجات وأضفها إلى سلتك.",
    "browseProducts": "تصفح المنتجات",
    "browseStoresAndTapTheHeart": "تصفح المتاجر واضغط على أيقونة القلب لحفظ المنتجات هنا",
    "browseTheMarketplaceAndSaveListings": "تصفح السوق واحفظ الإعلانات التي تعجبك",
    "buildingFloorApartmentOptional": "المبنى، الطابق، الشقة (اختياري)",
    "businessAddress": "عنوان العمل",
    "businessAddress2": "عنوان العمل *",
    "businessDescription": "وصف العمل",
    "businessName": "اسم العمل",
    "businessName2": "اسم العمل *",
    "busy": "مشغول",
    "calculating": "جارٍ الحساب...",
    "call": "اتصال",
    "callRider": "الاتصال بالسائق",
    "callSupport": "الاتصال بالدعم",
    "camera": "الكاميرا",
    "campaigns": "الحملات",
    "cancel": "إلغاء",
    "cancelBooking": "إلغاء الحجز",
    "cancelOrder": "إلغاء الطلب",
    "cancelOrder2": "إلغاء الطلب؟",
    "cancelSubscription": "إلغاء الاشتراك",
    "cancelYourSubscriptionPermanently": "إلغاء اشتراكك بشكل دائم",
    "cannotAddItemProductNotFound": "لا يمكن إضافة المنتج — المنتج غير موجود",
    "cannotDelete": "لا يمكن الحذف",
    "cannotIdentifyStoreForThisOrder": "لا يمكن تحديد المتجر لهذا الطلب",
    "carousel": "عرض دوار",
    "cartCleared": "تم تفريغ السلة",
    "categories": "الفئات",
    "categoriesManagement": "إدارة الفئات",
    "category": "الفئة",
    "categoryName": "اسم الفئة",
    "categoryType": "نوع الفئة",
    "changePassword": "تغيير كلمة المرور",
    "changePlan": "تغيير الخطة",
    "chat": "محادثة",
    "chatWith": "الدردشة مع",
    "chatWithDriver": "الدردشة مع السائق",
    "chatWithSeller": "الدردشة مع البائع",
    "chatWithUs": "تحدث معنا",
    "checkout": "الدفع",
    "chooseFromGallery": "اختر من المعرض",
    "choosePhoto": "اختر صورة",
    "city": "المدينة",
    "clear": "مسح",
    "clearAll": "مسح الكل",
    "clearCart": "تفريغ السلة",
    "clearChat": "مسح المحادثة",
    "clearFilters": "مسح الفلاتر",
    "clearSearch": "مسح البحث",
    "close": "إغلاق",
    "closed": "مغلق",
    "code": "الرمز",
    "completed": "مكتمل",
    "completedDeliveries": "التوصيلات المكتملة",
    "completedOrders": "الطلبات المكتملة",
    "completionRate": "معدل الإكمال",
    "confirm": "تأكيد",
    "confirmAddress": "تأكيد العنوان",
    "confirmBooking": "تأكيد الحجز",
    "confirmDelivery": "تأكيد التوصيل",
    "confirmLocation": "تأكيد الموقع",
    "confirmOrder": "تأكيد الطلب",
    "confirmPassword": "تأكيد كلمة المرور",
    "confirmPickup": "تأكيد الاستلام",
    "confirmed": "مؤكد",
    "connectingToSupabase": "جارٍ الاتصال بـ Supabase...",
    "connectionFailed": "فشل الاتصال",
    "contact": "اتصل",
    "contactInformation": "معلومات الاتصال",
    "contactNumber": "رقم الاتصال",
    "contactUs": "اتصل بنا",
    "continueAsCustomer": "المتابعة كعميل",
    "continueAsDriver": "المتابعة كسائق",
    "continueAsMerchant": "المتابعة كتاجر",
    "continueText": "متابعة",
    "conversation": "المحادثة",
    "copy": "نسخ",
    "copyAddress": "نسخ العنوان",
    "couldNotLaunchPhone": "تعذر فتح تطبيق الهاتف",
    "couldNotOpenMaps": "تعذر فتح الخرائط",
    "country": "البلد",
    "createAd": "إنشاء إعلان",
    "createCategory": "إنشاء فئة",
    "createListing": "إنشاء إعلان",
    "createNewListing": "إنشاء إعلان جديد",
    "createProduct": "إنشاء منتج",
    "createStore": "إنشاء متجر",
    "createdSuccessfully": "تم الإنشاء بنجاح",
    "currentPlan": "الخطة الحالية",
    "currentPassword": "كلمة المرور الحالية",
    "customer": "عميل",
    "customerHome": "الصفحة الرئيسية للعميل",
    "customerReviews": "تقييمات العملاء",
    "daily": "يومي",
    "dailyGoal": "الهدف اليومي",
    "darkMode": "الوضع الداكن",
    "dashboard": "لوحة التحكم",
    "date": "التاريخ",
    "days": "30 يوم",
    "days2": "7 أيام",
    "days3": "90 يوم",
    "deactivate": "تعطيل",
    "dealsOfTheDay": "عروض اليوم",
    "decline": "رفض",
    "default2": "افتراضي",
    "delete": "حذف",
    "deleteAccount": "حذف الحساب",
    "deleteAd": "حذف الإعلان",
    "deleteConversation": "حذف المحادثة",
    "deleteProduct": "حذف المنتج",
    "deleteStore": "حذف المتجر",
    "deletedSuccessfully": "تم الحذف بنجاح",
    "delivered": "تم التوصيل",
    "deliveries": "التوصيلات",
    "deliveriesOverTime": "التوصيلات عبر الزمن",
    "delivery": "التوصيل",
    "deliveryAddress": "عنوان التوصيل",
    "deliveryDetails": "تفاصيل التوصيل",
    "deliveryDistance": "مسافة التوصيل",
    "deliveryFee": "رسوم التوصيل",
    "deliveryInstructions": "تعليمات التوصيل",
    "deliveryPreferences": "تفضيلات التوصيل",
    "deliveryStatus": "حالة التوصيل",
    "deliveryTime": "وقت التوصيل",
    "deliveryTracking": "تتبع التوصيل",
    "description": "الوصف",
    "details": "التفاصيل",
    "didNotReceiveCode": "لم تستلم الرمز؟",
    "discount": "خصم",
    "discountPercent": "نسبة الخصم",
    "dismiss": "تجاهل",
    "distance": "المسافة",
    "distanceFee": "رسوم المسافة",
    "done": "تم",
    "dontHaveAnAccountSignUp": "ليس لديك حساب؟ سجّل الآن",
    "download": "تحميل",
    "driver": "سائق",
    "driverApplication": "طلب سائق",
    "driverApplicationRequirements": "متطلبات طلب السائق",
    "driverApplications": "طلبات السائقين",
    "driverDashboard": "لوحة تحكم السائق",
    "driverHome": "الصفحة الرئيسية للسائق",
    "driverManagement": "إدارة السائقين",
    "driverPerformance": "أداء السائق",
    "driverProfile": "ملف السائق",
    "driverRatings": "تقييمات السائق",
    "driverSettings": "إعدادات السائق",
    "drivers": "السائقون",
    "driversOnDuty": "السائقون في الخدمة",
    "earnings": "الأرباح",
    "earningsOverview": "نظرة عامة على الأرباح",
    "earningsThisWeek": "أرباح هذا الأسبوع",
    "edit": "تعديل",
    "editAddress": "تعديل العنوان",
    "editCategory": "تعديل الفئة",
    "editListing": "تعديل الإعلان",
    "editProduct": "تعديل المنتج",
    "editProfile": "تعديل الملف الشخصي",
    "editStore": "تعديل المتجر",
    "email": "البريد الإلكتروني",
    "emailAddress": "عنوان البريد الإلكتروني",
    "emailCannotBeChangedHere": "لا يمكن تغيير البريد الإلكتروني هنا",
    "emailVerification": "التحقق من البريد الإلكتروني",
    "emailVerified": "تم التحقق من البريد الإلكتروني",
    "empty": "فارغ",
    "emptyCart": "السلة فارغة",
    "enableNotifications": "تفعيل الإشعارات",
    "endDate": "تاريخ الانتهاء",
    "enterAddress": "أدخل العنوان",
    "enterAmount": "أدخل المبلغ",
    "enterCode": "أدخل الرمز",
    "enterEmail": "أدخل البريد الإلكتروني",
    "enterMessage": "أدخل رسالة",
    "enterName": "أدخل الاسم",
    "enterPassword": "أدخل كلمة المرور",
    "enterPhone": "أدخل رقم الهاتف",
    "enterPrice": "أدخل السعر",
    "enterPromoCode": "أدخل رمز الخصم",
    "enterYourEmailAddress": "أدخل عنوان بريدك الإلكتروني",
    "enterYourFullName": "أدخل اسمك الكامل",
    "enterYourMessage": "أدخل رسالتك...",
    "enterYourPassword": "أدخل كلمة المرور",
    "error": "خطأ",
    "errorLoadingData": "خطأ في تحميل البيانات",
    "estimatedDelivery": "التوصيل المتوقع",
    "estimatedTime": "الوقت المتوقع",
    "expired": "منتهي الصلاحية",
    "explore": "استكشاف",
    "exploreCategories": "استكشف الفئات",
    "exploreMarketplace": "استكشف السوق",
    "exploreStores": "استكشف المتاجر",
    "failed": "فشل",
    "failedToLoadData": "فشل في تحميل البيانات",
    "failedToUpdateProfile": "فشل في تحديث الملف الشخصي",
    "favorites": "المفضلة",
    "featured": "★ مميز",
    "featuredCategories": "الفئات المميزة",
    "featuredProducts": "المنتجات المميزة",
    "featuredStores": "المتاجر المميزة",
    "filter": "فلتر",
    "filterBy": "فلترة حسب",
    "filters": "الفلاتر",
    "findStoresNearYou": "اعثر على متاجر قريبة منك",
    "firstName": "الاسم الأول",
    "forYou": "لك",
    "forgotPassword": "نسيت كلمة المرور؟",
    "free": "مجاني",
    "freeDelivery": "توصيل مجاني",
    "freshCart": "FreshCart",
    "from": "من",
    "fullName": "الاسم الكامل",
    "gallery": "المعرض",
    "general": "عام",
    "getDirections": "الحصول على الاتجاهات",
    "getStarted": "ابدأ الآن",
    "goBack": "العودة",
    "goOffline": "الذهاب دون اتصال",
    "goOnline": "الذهاب متصل",
    "goalReached": "تم تحقيق الهدف!",
    "gridView": "عرض شبكي",
    "help": "مساعدة",
    "helpCenter": "مركز المساعدة",
    "helpSupport": "المساعدة والدعم",
    "high": "مرتفع",
    "highToLow": "من الأعلى للأقل",
    "history": "السجل",
    "home": "الرئيسية",
    "howCanIHelpYou": "كيف يمكنني مساعدتك؟",
    "howWouldYouRateYourDelivery": "كيف تقيّم توصيلك؟",
    "iAgreeToTheTermsAndConditions": "أوافق على الشروط والأحكام",
    "imageUrl": "رابط الصورة",
    "inProgress": "قيد التنفيذ",
    "inStock": "متوفر",
    "inactive": "غير نشط",
    "info": "معلومات",
    "instructions": "التعليمات",
    "invalidEmail": "بريد إلكتروني غير صالح",
    "invalidPhoneNumber": "رقم هاتف غير صالح",
    "inventory": "المخزون",
    "inventoryManagement": "إدارة المخزون",
    "items": "المنتجات",
    "itemsInCart": "المنتجات في السلة",
    "joinAsADriver": "انضم كسائق",
    "keepShopping": "تابع التسوق",
    "language": "اللغة",
    "lastName": "اسم العائلة",
    "lastUpdated": "آخر تحديث",
    "leaveAReview": "اترك تقييماً",
    "lightMode": "الوضع الفاتح",
    "listView": "عرض قائمة",
    "listing": "إعلان",
    "listings": "الإعلانات",
    "loading": "جارٍ التحميل...",
    "location": "الموقع",
    "locationPermission": "إذن الموقع",
    "locationServices": "خدمات الموقع",
    "logIn": "تسجيل الدخول",
    "logOut": "تسجيل الخروج",
    "login": "تسجيل الدخول",
    "loginToContinue": "سجّل الدخول للمتابعة",
    "logout": "تسجيل الخروج",
    "low": "منخفض",
    "lowToHigh": "من الأقل للأعلى",
    "loyalty": "الولاء",
    "loyaltyRewards": "مكافآت الولاء",
    "manage": "إدارة",
    "manageAddresses": "إدارة العناوين",
    "manageOrders": "إدارة الطلبات",
    "manageProducts": "إدارة المنتجات",
    "manageStores": "إدارة المتاجر",
    "manageSubscription": "إدارة الاشتراك",
    "map": "الخريطة",
    "mapView": "عرض الخريطة",
    "marketplace": "السوق",
    "markAsDefault": "تعيين كافتراضي",
    "markAsRead": "تحديد كمقروء",
    "medium": "متوسط",
    "menu": "القائمة",
    "merchant": "تاجر",
    "merchantApplication": "طلب تاجر",
    "merchantApplicationRequirements": "متطلبات طلب التاجر",
    "merchantDashboard": "لوحة تحكم التاجر",
    "merchantHome": "الصفحة الرئيسية للتاجر",
    "merchantProfile": "ملف التاجر",
    "merchantReviews": "تقييمات التاجر",
    "merchantStore": "متجر التاجر",
    "merchants": "التجار",
    "message": "رسالة",
    "messageDriver": "مراسلة السائق",
    "messages": "الرسائل",
    "minimumOrder": "الحد الأدنى للطلب",
    "monthly": "شهري",
    "more": "المزيد",
    "mostPopular": "الأكثر شعبية",
    "myAccount": "حسابي",
    "myAddresses": "عناويني",
    "myBookings": "حجوزاتي",
    "myFavorites": "مفضلاتي",
    "myListings": "إعلاناتي",
    "myOrders": "طلباتي",
    "myStore": "متجري",
    "myWallet": "محفظتي",
    "name": "الاسم",
    "nearby": "قريب",
    "nearbyStores": "المتاجر القريبة",
    "newArrivals": "وصل حديثاً",
    "newListing": "إعلان جديد",
    "newOrder": "طلب جديد",
    "newPassword": "كلمة المرور الجديدة",
    "newProduct": "منتج جديد",
    "next": "التالي",
    "no": "لا",
    "noActiveOrders": "لا توجد طلبات نشطة",
    "noAddressesYet": "لا توجد عناوين بعد",
    "noBookingsYet": "لا توجد حجوزات بعد",
    "noCategoriesFound": "لم يتم العثور على فئات",
    "noConversationsYet": "لا توجد محادثات بعد",
    "noDataAvailable": "لا توجد بيانات متاحة",
    "noDeliveriesYet": "لا توجد توصيلات بعد",
    "noDriversAvailable": "لا يوجد سائقون متاحون",
    "noFavoritesYet": "لا توجد مفضلات بعد",
    "noItemsInCart": "لا توجد منتجات في السلة",
    "noListingsYet": "لا توجد إعلانات بعد",
    "noMessages": "لا توجد رسائل",
    "noNotifications": "لا توجد إشعارات",
    "noOrdersFound": "لم يتم العثور على طلبات",
    "noOrdersYet": "لا توجد طلبات بعد",
    "noProductsFound": "لم يتم العثور على منتجات",
    "noResultsFound": "لم يتم العثور على نتائج",
    "noReviews": "لا توجد تقييمات",
    "noReviewsYet": "لا توجد تقييمات بعد",
    "noStoresFound": "لم يتم العثور على متاجر",
    "none": "لا شيء",
    "notAvailable": "غير متاح",
    "notVerified": "غير موثق",
    "notification": "إشعار",
    "notificationPreferences": "تفضيلات الإشعارات",
    "notifications": "الإشعارات",
    "off": "إيقاف",
    "offline": "غير متصل",
    "ok": "حسناً",
    "on": "تشغيل",
    "onTheWay": "في الطريق",
    "online": "متصل",
    "open": "مفتوح",
    "openNow": "مفتوح الآن",
    "optional": "اختياري",
    "order": "طلب",
    "orderAgain": "اطلب مرة أخرى",
    "orderCancelled": "تم إلغاء الطلب",
    "orderCompleted": "تم إكمال الطلب",
    "orderConfirmed": "تم تأكيد الطلب",
    "orderDate": "تاريخ الطلب",
    "orderDetails": "تفاصيل الطلب",
    "orderHistory": "سجل الطلبات",
    "orderManagement": "إدارة الطلبات",
    "orderNumber": "رقم الطلب",
    "orderPlaced": "تم تقديم الطلب",
    "orderPlacedSuccessfully": "تم تقديم الطلب بنجاح!",
    "orderStatus": "حالة الطلب",
    "orderSummary": "ملخص الطلب",
    "orderTotal": "إجمالي الطلب",
    "orderTracking": "تتبع الطلب",
    "orders": "الطلبات",
    "ordersManagement": "إدارة الطلبات",
    "ordersThisMonth": "طلبات هذا الشهر",
    "ordersToday": "طلبات اليوم",
    "outOfStock": "نفذ المخزون",
    "overview": "نظرة عامة",
    "password": "كلمة المرور",
    "passwordResetEmailSent": "تم إرسال بريد إعادة تعيين كلمة المرور",
    "passwordsMustMatch": "كلمات المرور يجب أن تتطابق",
    "pause": "إيقاف مؤقت",
    "payment": "الدفع",
    "paymentMethod": "طريقة الدفع",
    "paymentMethods": "طرق الدفع",
    "pending": "معلّق",
    "pendingApproval": "بانتظار الموافقة",
    "pendingOrders": "الطلبات المعلّقة",
    "performance": "الأداء",
    "performanceDashboard": "لوحة الأداء",
    "phone": "الهاتف",
    "phoneNumber": "رقم الهاتف",
    "phoneVerification": "التحقق من الهاتف",
    "pickUp": "استلام",
    "pickUpLocation": "موقع الاستلام",
    "placeOrder": "تقديم الطلب",
    "plan": "الخطة",
    "plans": "الخطط",
    "pleaseCheckYourEmailAndVerify": "يرجى التحقق من بريدك الإلكتروني والتأكيد",
    "pleaseEnterAValidEmail": "يرجى إدخال بريد إلكتروني صالح",
    "pleaseEnterYourEmail": "يرجى إدخال بريدك الإلكتروني",
    "pleaseEnterYourName": "يرجى إدخال اسمك",
    "pleaseEnterYourPassword": "يرجى إدخال كلمة المرور",
    "pleaseEnterYourPhone": "يرجى إدخال رقم هاتفك",
    "pleaseFillInAllRequiredFields": "يرجى ملء جميع الحقول المطلوبة",
    "pleaseLoginFirst": "يرجى تسجيل الدخول أولاً",
    "pleaseSelectACategory": "يرجى اختيار فئة",
    "pleaseSelectADeliveryAddress": "يرجى اختيار عنوان توصيل",
    "pleaseSelectAPaymentMethod": "يرجى اختيار طريقة دفع",
    "pleaseTryAgain": "يرجى المحاولة مرة أخرى",
    "pleaseWait": "يرجى الانتظار...",
    "points": "النقاط",
    "popular": "شائع",
    "popularProducts": "المنتجات الشائعة",
    "popularStores": "المتاجر الشائعة",
    "postAd": "نشر إعلان",
    "preparing": "جارٍ التحضير",
    "preparingYourOrder": "جارٍ تحضير طلبك",
    "preview": "معاينة",
    "price": "السعر",
    "priceRange": "نطاق السعر",
    "privacy": "الخصوصية",
    "privacyPolicy": "سياسة الخصوصية",
    "privacySecurity": "الخصوصية والأمان",
    "product": "المنتج",
    "productDetails": "تفاصيل المنتج",
    "productName": "اسم المنتج",
    "products": "المنتجات",
    "profile": "الملف الشخصي",
    "profileUpdated": "تم تحديث الملف الشخصي",
    "profileUpdatedSuccessfully": "تم تحديث الملف الشخصي بنجاح",
    "promoCode": "رمز الخصم",
    "promoCodeApplied": "تم تطبيق رمز الخصم",
    "promotions": "العروض",
    "publish": "نشر",
    "quantity": "الكمية",
    "quickAdd": "إضافة سريعة",
    "rate": "تقييم",
    "rateDelivery": "تقييم التوصيل",
    "rateOrder": "تقييم الطلب",
    "rateStore": "تقييم المتجر",
    "rateYourExperience": "قيّم تجربتك",
    "rating": "التقييم",
    "readyForPickup": "جاهز للاستلام",
    "recentOrders": "الطلبات الأخيرة",
    "recentSearches": "عمليات البحث الأخيرة",
    "recommended": "موصى به",
    "refresh": "تحديث",
    "reject": "رفض",
    "rejectDriver": "رفض السائق",
    "rejectMerchant": "رفض التاجر",
    "rejected": "مرفوض",
    "rememberMe": "تذكرني",
    "remove": "إزالة",
    "removeFromCart": "إزالة من السلة",
    "removeFromFavorites": "إزالة من المفضلة",
    "reorder": "إعادة الطلب",
    "report": "بلاغ",
    "requestSent": "تم إرسال الطلب",
    "required": "مطلوب",
    "resend": "إعادة إرسال",
    "resendCode": "إعادة إرسال الرمز",
    "reset": "إعادة تعيين",
    "resetPassword": "إعادة تعيين كلمة المرور",
    "results": "النتائج",
    "retry": "إعادة المحاولة",
    "revenue": "الإيرادات",
    "revenueOverview": "نظرة عامة على الإيرادات",
    "review": "تقييم",
    "reviews": "التقييمات",
    "role": "الدور",
    "roleUpgrade": "ترقية الدور",
    "roleUpgradeRequest": "طلب ترقية الدور",
    "save": "حفظ",
    "saveAddress": "حفظ العنوان",
    "saveChanges": "حفظ التغييرات",
    "saveForLater": "حفظ لاحقاً",
    "saved": "محفوظ",
    "savedAddresses": "العناوين المحفوظة",
    "savedForLater": "محفوظ لاحقاً",
    "search": "بحث",
    "searchCategories": "بحث في الفئات",
    "searchForProductsStoresAnd": "ابحث عن المنتجات والمتاجر والمزيد",
    "searchProducts": "بحث المنتجات",
    "searchResults": "نتائج البحث",
    "searchStores": "بحث المتاجر",
    "security": "الأمان",
    "seeAll": "عرض الكل",
    "selectAddress": "اختر عنوان",
    "selectCategory": "اختر فئة",
    "selectDate": "اختر التاريخ",
    "selectLanguage": "اختر اللغة",
    "selectLocation": "اختر الموقع",
    "selectPaymentMethod": "اختر طريقة الدفع",
    "selectStore": "اختر متجر",
    "selectTime": "اختر الوقت",
    "seller": "البائع",
    "sellerInformation": "معلومات البائع",
    "send": "إرسال",
    "sendMessage": "إرسال رسالة",
    "serviceBooking": "حجز خدمة",
    "services": "الخدمات",
    "settings": "الإعدادات",
    "share": "مشاركة",
    "shipping": "الشحن",
    "shop": "تسوق",
    "shopNow": "تسوق الآن",
    "shoppingCart": "سلة التسوق",
    "showLess": "عرض أقل",
    "showMore": "عرض المزيد",
    "signIn": "تسجيل الدخول",
    "signInToContinue": "سجّل الدخول للمتابعة",
    "signInWithGoogle": "تسجيل الدخول بجوجل",
    "signOut": "تسجيل الخروج",
    "signUp": "إنشاء حساب",
    "skip": "تخطي",
    "sold": "مباع",
    "soldOut": "نفذت الكمية",
    "sortBy": "ترتيب حسب",
    "specialInstructions": "تعليمات خاصة",
    "startDate": "تاريخ البدء",
    "startDelivering": "ابدأ التوصيل",
    "startShopping": "ابدأ التسوق",
    "statistics": "الإحصائيات",
    "status": "الحالة",
    "store": "المتجر",
    "storeDetails": "تفاصيل المتجر",
    "storeManagement": "إدارة المتجر",
    "storeName": "اسم المتجر",
    "storeProfile": "ملف المتجر",
    "storeRating": "تقييم المتجر",
    "stores": "المتاجر",
    "submit": "إرسال",
    "submitApplication": "تقديم الطلب",
    "submitOrder": "تقديم الطلب",
    "submitReview": "إرسال التقييم",
    "subscription": "الاشتراك",
    "subscriptionManagement": "إدارة الاشتراك",
    "subscriptionPlans": "خطط الاشتراك",
    "subtotal": "المجموع الفرعي",
    "success": "نجاح",
    "successfullyUpdated": "تم التحديث بنجاح",
    "summary": "الملخص",
    "support": "الدعم",
    "support2": "الدعم على مدار الساعة",
    "taxAndFees": "الضرائب والرسوم",
    "termsAndConditions": "الشروط والأحكام",
    "termsOfService": "شروط الخدمة",
    "thankYou": "شكراً لك",
    "thankYouForYourOrder": "شكراً لك على طلبك!",
    "theme": "المظهر",
    "thisWeek": "هذا الأسبوع",
    "time": "الوقت",
    "tipForDriver": "إكرامية للسائق",
    "to": "إلى",
    "today": "اليوم",
    "todayEarnings": "أرباح اليوم",
    "todayOrders": "طلبات اليوم",
    "topProducts": "أفضل المنتجات",
    "topRated": "الأعلى تقييماً",
    "topStores": "أفضل المتاجر",
    "total": "الإجمالي",
    "totalDeliveries": "إجمالي التوصيلات",
    "totalEarnings": "إجمالي الأرباح",
    "totalOrders": "إجمالي الطلبات",
    "totalProducts": "إجمالي المنتجات",
    "totalRevenue": "إجمالي الإيرادات",
    "totalUsers": "إجمالي المستخدمين",
    "tracking": "التتبع",
    "trackingNumber": "رقم التتبع",
    "trackOrder": "تتبع الطلب",
    "transactions": "المعاملات",
    "tryAgain": "حاول مرة أخرى",
    "type": "النوع",
    "typeAMessage": "اكتب رسالة...",
    "unfavorite": "إلغاء المفضلة",
    "unit": "الوحدة",
    "unknown": "غير معروف",
    "unlimited": "غير محدود",
    "update": "تحديث",
    "updateAddress": "تحديث العنوان",
    "updateProfile": "تحديث الملف الشخصي",
    "updateStore": "تحديث المتجر",
    "updated": "تم التحديث",
    "updatedSuccessfully": "تم التحديث بنجاح",
    "upload": "رفع",
    "uploadImage": "رفع صورة",
    "uploadPhoto": "رفع صورة",
    "usersManagement": "إدارة المستخدمين",
    "vehicle": "المركبة",
    "vehicleType": "نوع المركبة",
    "verified": "موثق",
    "verify": "تحقق",
    "verifyEmail": "تحقق من البريد الإلكتروني",
    "verifyOtp": "تحقق من رمز OTP",
    "verifyPhone": "تحقق من الهاتف",
    "version": "الإصدار",
    "view": "عرض",
    "viewAll": "عرض الكل",
    "viewAsCustomer": "عرض كعميل",
    "viewAssignedOrdersStartDeliveries": "عرض الطلبات المعينة وبدء التوصيلات",
    "viewCart": "عرض السلة",
    "viewCustomerHome": "عرض صفحة العميل",
    "viewMarketplace": "عرض السوق",
    "viewOrderHistory": "عرض سجل الطلبات",
    "viewSimilar": "عرض المشابه",
    "visibleToUsers": "مرئي للمستخدمين",
    "wallet": "المحفظة",
    "weekly": "أسبوعي",
    "weeklyEarningsTrend": "اتجاه الأرباح الأسبوعي",
    "weeklySummary": "الملخص الأسبوعي",
    "yes": "نعم",
    "yesCancel": "نعم، إلغاء",
    "youAlreadyRatedThisDelivery": "لقد قيّمت هذا التوصيل بالفعل",
    "youAlreadyRatedThisStore": "لقد قيّمت هذا المتجر بالفعل",
    "youCanOnlyRateDeliveredOrders": "يمكنك تقييم الطلبات المسلّمة فقط",
    "youCannotMessageYourOwnListing": "لا يمكنك مراسلة إعلانك الخاص",
    "youDoNotHaveAdminPrivileges": "ليس لديك صلاحيات المسؤول.",
    "youDoNotHavePermissionTo": "ليس لديك إذن للوصول إلى هذه الصفحة",
    "youMightAlsoLike": "قد يعجبك أيضاً",
    "youMustBeLoggedInTo": "يجب أن تكون مسجل الدخول لرفع الصور",
    "youNeedToApplyAsA": "تحتاج إلى التقدم كتاجر أولاً",
    "yourCartIsEmpty": "سلتك فارغة",
    "yourConversations": "محادثاتك",
    "yourDriver": "سائقك",
    "yourDriverApplicationIsUnderReview": "طلب السائق الخاص بك قيد المراجعة",
    "yourMerchantApplicationIsUnderReview": "طلب التاجر الخاص بك قيد المراجعة",
    "yourEmailCom": "your@email.com",
}

def main():
    os.makedirs(L10N_DIR, exist_ok=True)

    # Build English ARB
    en_arb = {"@@locale": "en"}
    for key, en_value in strings.items():
        en_arb[key] = en_value

    # Build Arabic ARB
    ar_arb = {"@@locale": "ar"}
    missing_count = 0
    for key, en_value in strings.items():
        if key in AR_TRANSLATIONS:
            ar_arb[key] = AR_TRANSLATIONS[key]
        else:
            # For keys without manual translation, use English as fallback
            # and mark with TODO
            ar_arb[key] = en_value  # fallback to English
            missing_count += 1

    # Write English ARB
    en_path = os.path.join(L10N_DIR, 'app_en.arb')
    with open(en_path, 'w', encoding='utf-8') as f:
        json.dump(en_arb, f, indent=2, ensure_ascii=False)
    print(f"Written {len(en_arb) - 1} strings to {en_path}")

    # Write Arabic ARB
    ar_path = os.path.join(L10N_DIR, 'app_ar.arb')
    with open(ar_path, 'w', encoding='utf-8') as f:
        json.dump(ar_arb, f, indent=2, ensure_ascii=False)
    print(f"Written {len(ar_arb) - 1} strings to {ar_path}")
    print(f"Missing Arabic translations (using English fallback): {missing_count}")

    # List missing keys for reference
    if missing_count > 0:
        missing_keys = [k for k in strings if k not in AR_TRANSLATIONS]
        missing_path = os.path.join(SCRIPT_DIR, 'missing_ar_translations.json')
        with open(missing_path, 'w', encoding='utf-8') as f:
            missing_dict = {k: strings[k] for k in missing_keys}
            json.dump(missing_dict, f, indent=2, ensure_ascii=False)
        print(f"Missing keys written to {missing_path}")

if __name__ == '__main__':
    main()
